"""First Schema

Revision ID: 1ffe4ca0aee7
Revises: 
Create Date: 2026-09-07 05:58:06.696772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffe4ca0aee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachingscenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.Enum('ai', 'bank'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempt_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempt_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('interview_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('contact_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_request_employer_id'), ['employer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_request_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=150), nullable=False),
    sa.Column('cac_number', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['employer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id_card', sa.String(length=255), nullable=True),
    sa.Column('picture_upload', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['employer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('exam_score', sa.Float(), nullable=True),
    sa.Column('video_score', sa.Float(), nullable=True),
    sa.Column('reference_score', sa.Float(), nullable=True),
    sa.Column('profile_score', sa.Float(), nullable=True),
    sa.Column('composite', sa.Float(), nullable=True),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_composite'), ['composite'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_teacher_id'), ['teacher_id'], unique=True)

    op.create_table('recruitment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'terminated', name='recruitment_status'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruitment_history_employer_id'), ['employer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruitment_history_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('videosubmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'ai_reviewed', 'assigned', 'in_progress', 'completed', 'failed', name='video_status'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['teachingscenario.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videosubmission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videosubmission_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videosubmission_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('work_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_end_date_after_start_date'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_history_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_type', sa.Enum('ai', 'human'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videosubmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_video_id'), ['video_id'], unique=False)

    op.create_table('review_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', 'cancelled', name='assignment_status'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videosubmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_assignment_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_assignment_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_assignment_video_id'))
        batch_op.drop_index(batch_op.f('ix_review_assignment_reviewer_id'))

    op.drop_table('review_assignment')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_video_id'))
        batch_op.drop_index(batch_op.f('ix_review_reviewer_id'))

    op.drop_table('review')
    with op.batch_alter_table('work_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_history_teacher_id'))

    op.drop_table('work_history')
    with op.batch_alter_table('videosubmission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videosubmission_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_videosubmission_scenario_id'))

    op.drop_table('videosubmission')
    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_teacher_id'))

    op.drop_table('reference')
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruitment_history_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_recruitment_history_employer_id'))

    op.drop_table('recruitment_history')
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_rating_composite'))

    op.drop_table('rating')
    op.drop_table('parent')
    op.drop_table('organization')
    with op.batch_alter_table('interview_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_request_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_interview_request_employer_id'))

    op.drop_table('interview_request')
    with op.batch_alter_table('exam_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempt_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_exam_attempt_exam_id'))

    op.drop_table('exam_attempt')
    op.drop_table('teacher')
    op.drop_table('reviewer')
    op.drop_table('employer')
    op.drop_table('user')
    op.drop_table('teachingscenario')
    op.drop_table('exam')
    # ### end Alembic commands ###
