"""add documents to teacher

Revision ID: 595840111a01
Revises: 1ffe4ca0aee7
Create Date: 2026-09-10 23:38:40.305957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595840111a01'
down_revision = '1ffe4ca0aee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('documents')

    # ### end Alembic commands ###
